name: Build PXL - macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install homebrew & Install Requirements (ldid,make,xz) #Installing make because >> https://theos.dev/docs/parallel-building <<
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install ldid make xz
          echo PATH=\"$(brew --prefix make)/libexec/gnubin:\$PATH\" >> .env

      - name: Install Theos
        uses: actions/checkout@v3
        with:
          repository: theos/theos
          path: theos
          submodules: recursive

      - name: Export Theos Install # Do not remove this step its critical.
        run: |
         echo "export THEOS=$(pwd)/theos" >> .env

      - name: Download iPhoneOS 14.1 SDK # Download SDKs
        run: |
          cd $(pwd)/theos/sdks
          wget -q https://www.dropbox.com/s/jvonok3de24ibsz/14.1.zip > /dev/null 2>&1
          unzip 14.1.zip > /dev/null 2>&1

      - name: Download SparkColourPicker
        run: |
          cd $(pwd)/theos/include
          wget -q https://raw.githubusercontent.com/SparkDev97/libSparkColourPicker/master/headers/SparkColourPickerView.h > /dev/null 2>&1
          wget -q https://raw.githubusercontent.com/SparkDev97/libSparkColourPicker/master/headers/SparkColourPickerUtils.h > /dev/null 2>&1
          cd $(pwd)/theos/lib
          wget -q https://raw.githubusercontent.com/SparkDev97/libSparkColourPicker/master/lib/libsparkcolourpicker.dylib > /dev/null 2>&1
          sudo chmod 755 $(pwd)/theos/lib/libsparkcolourpicker.dylib

      - name: Build Tweak
        run: |
          source .env
          make clean package
          cp packages/*.deb $(pwd)

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: PXL.deb # Name of .deb file shown on first page
          path: |
            packages/*.deb
